name: Rubocop

# Run every time a commit is pushed to master, or a pull request opened against
# master.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  rubocop:
    name: Rubocopchecks
    runs-on: ubuntu-latest
    steps:
      - name: Run Rubocop
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
