name: Test Suite

# Run every time a commit is pushed to master, or a pull request opened against
# master.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_matrix:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
          - 3.0

    env:
      TEST_CHECKS: 100

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Build C library
      run: bin/setup
    - name: Test C library
      run: cd ext/argon2_wrap/ && make test && cd ../..
    - name: Run tests
      run: bundle exec rake
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    needs: [test_matrix, rubocop]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
