name: Test Suite

# Run against all commits and pull requests.
on: [ push, pull_request ]

jobs:
  test_matrix:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0

    env:
      TEST_CHECKS: 100

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Initialize Git Submodules
        run: git submodule update --init --recursive
      - name: Build Argon2 C library
        run: bin/setup
      - name: Test Argon2 C library
        run: bin/test
      - name: Run tests
        run: bundle exec rake test

  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rake rubocop

# TODO: Add code coverage testing (coveralls)
# TODO: Add documentation/maintainability testing?
# TODO: Add dependency testing? (bundle audit)

  finish:
    runs-on: ubuntu-latest
    needs: [ test_matrix, rubocop ]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
